### ISSUE TITLE
Unknown tag 'X'

### ISSUE THREAD

**Issue by yinan-symphony** [amannocci/temply#8]
**Describe the bug**
when executing temply --keep-template -o on a template file containing %X, the command fails.

opt/symphony/app/conf$ temply --keep-template -o log4j2-spring.xml log4j2-spring.xml.tpl
Traceback (most recent call last):
  File "temply", line 5, in <module>
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "temply/temply.py", line 70, in main
  File "jinja2/environment.py", line 883, in get_template
  File "jinja2/environment.py", line 857, in _load_template
  File "jinja2/loaders.py", line 127, in load
  File "jinja2/environment.py", line 638, in compile
  File "jinja2/environment.py", line 832, in handle_exception
  File "jinja2/_compat.py", line 28, in reraise
  File "/opt/symphony/app/conf/log4j2-spring.xml.tpl", line 12, in template
    <PatternLayout pattern="%d{yyyy-MM-dd'T'HH:mm:ss,SSS}{UTC}Z %-5level [%t-%T] %C{-15} : %notEmpty{%X{X-Trace-Id} -} %encode{ %m }{CRLF} %n%xEx" />
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'X'.
[7751] Failed to execute script 'temply' due to unhandled exception!

**To Reproduce**
 - Create a xml file and add <PatternLayout pattern="%d{yyyy-MM-dd'T'HH:mm:ss,SSS}{UTC}Z %-5level [%t-%T] %C{-15} : %notEmpty{%X{X-Trace-Id} -} %encode{ %m }{CRLF} %n%xEx" />,
 - run the command temply --keep-template -o

**Expected behavior**
command runs successful and the file gets rendered.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by amannocci** [comment]
Hi @yinan-symphony, can you provide an example of the template content ? (Line 12 apparently).

**Comment by yinan-symphony** [comment]
oh, strange, i put the example in the description, but somehow it s removed

**Comment by yinan-symphony** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<Configuration>
    <Properties>
        <Property name="LOG_PATH">/opt/symphony/app/data/logs</Property>
        <Property name="LOG_FILE">application</Property>
        <Property name="LOG_FILE_MAX_SIZE">10MB</Property>
        <Property name="LOG_DATEFORMAT_PATTERN">yyyy-MM-dd-HH</Property>
        <Property name="LOG_FILE_MAX_HISTORY">5</Property>
    </Properties>
    <Appenders>
        <RollingFile name="File" fileName="${sys:LOG_PATH}/${sys:LOG_FILE}.log" filePattern="${sys:LOG_PATH}/$${date:yyyy-MM}/${sys:LOG_FILE}-%d{${sys:LOG_DATEFORMAT_PATTERN}}-%i.log.gz">
            <PatternLayout pattern="%d{yyyy-MM-dd'T'HH:mm:ss,SSS}{UTC}Z %-5level [%t-%T] %C{-15} : %notEmpty{%X{X-Trace-Id} -} %encode{ %m }{CRLF} %n%xEx" />
            <Policies>
                <OnStartupTriggeringPolicy />
                <SizeBasedTriggeringPolicy size="${sys:LOG_FILE_MAX_SIZE}" />
                <TimeBasedTriggeringPolicy />
            </Policies>
            <DefaultRolloverStrategy max="${sys:LOG_FILE_MAX_HISTORY}" />
        </RollingFile>
        <Console name="Console" target="SYSTEM_OUT" ignoreExceptions="true">
            <PatternLayout pattern="%highlight{%d{yyyy-MM-dd'T'HH:mm:ss,SSS}{UTC}Z %-5level} %style{[%t-%T]}{bright,blue} %style{%C{-15}}{bright,yellow} : %style{%notEmpty{%X{X-Trace-Id} -}}{green} %encode{ %m }{CRLF} %n%xEx" />
        </Console>
    </Appenders>
    <Loggers>
        {% for logger in (SPRING_LOGGING_LOGGERS | default("[]") | from_json) %}
        <Logger name="{{ logger.name }}" level="{{ logger.level | default('info') }}" additivity="false">
            <AppenderRef ref="Console" />
            {% if SPRING_LOGGING_ON_FILE is defined and SPRING_LOGGING_ON_FILE == 'true' %}
            <AppenderRef ref="File" />
            {% endif %}
        </Logger>
        {% endfor %}
        <Root level="info">
            <AppenderRef ref="Console" />
            {% if SPRING_LOGGING_ON_FILE is defined and SPRING_LOGGING_ON_FILE == 'true' %}
            <AppenderRef ref="File" />
            {% endif %}
        </Root>
    </Loggers>
</Configuration>`

**Comment by yinan-symphony** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<Configuration>
    <Properties>
        <Property name="LOG_PATH">/opt/symphony/app/data/logs</Property>
        <Property name="LOG_FILE">application</Property>
        <Property name="LOG_FILE_MAX_SIZE">10MB</Property>
        <Property name="LOG_DATEFORMAT_PATTERN">yyyy-MM-dd-HH</Property>
        <Property name="LOG_FILE_MAX_HISTORY">5</Property>
    </Properties>
    <Appenders>
        <RollingFile name="File" fileName="${sys:LOG_PATH}/${sys:LOG_FILE}.log" filePattern="${sys:LOG_PATH}/$${date:yyyy-MM}/${sys:LOG_FILE}-%d{${sys:LOG_DATEFORMAT_PATTERN}}-%i.log.gz">
            <PatternLayout pattern="%d{yyyy-MM-dd'T'HH:mm:ss,SSS}{UTC}Z %-5level [%t-%T] %C{-15} : %notEmpty{%X{X-Trace-Id} -} %encode{ %m }{CRLF} %n%xEx" />
            <Policies>
                <OnStartupTriggeringPolicy />
                <SizeBasedTriggeringPolicy size="${sys:LOG_FILE_MAX_SIZE}" />
                <TimeBasedTriggeringPolicy />
            </Policies>
            <DefaultRolloverStrategy max="${sys:LOG_FILE_MAX_HISTORY}" />
        </RollingFile>
        <Console name="Console" target="SYSTEM_OUT" ignoreExceptions="true">
            <PatternLayout pattern="%highlight{%d{yyyy-MM-dd'T'HH:mm:ss,SSS}{UTC}Z %-5level} %style{[%t-%T]}{bright,blue} %style{%C{-15}}{bright,yellow} : %style{%notEmpty{%X{X-Trace-Id} -}}{green} %encode{ %m }{CRLF} %n%xEx" />
        </Console>
    </Appenders>
    <Loggers>
        {% for logger in (SPRING_LOGGING_LOGGERS | default("[]") | from_json) %}
        <Logger name="{{ logger.name }}" level="{{ logger.level | default('info') }}" additivity="false">
            <AppenderRef ref="Console" />
            {% if SPRING_LOGGING_ON_FILE is defined and SPRING_LOGGING_ON_FILE == 'true' %}
            <AppenderRef ref="File" />
            {% endif %}
        </Logger>
        {% endfor %}
        <Root level="info">
            <AppenderRef ref="Console" />
            {% if SPRING_LOGGING_ON_FILE is defined and SPRING_LOGGING_ON_FILE == 'true' %}
            <AppenderRef ref="File" />
            {% endif %}
        </Root>
    </Loggers>
</Configuration>`

**Comment by yinan-symphony** [comment]
@amannocci i cannot make the format correct in the comment, i don't know why. basically the line 12 is
`<PatternLayout pattern="%d{yyyy-MM-dd'T'HH:mm:ss,SSS}{UTC}Z %-5level [%t-%T] %C{-15} : %notEmpty{%X{X-Trace-Id} -} %encode{ %m }{CRLF} %n%xEx" />`

**Comment by amannocci** [comment]
I see, It's related to Jinja interpretation of '{' and '}'.
You will have to escape the following sequence '{%X' using https://jinja.palletsprojects.com/en/3.0.x/templates/#escaping
I recommend the use of a "block raw" if you don't need to inject any data in the pattern layout.

**Comment by yinan-symphony** [comment]
@amannocci ok, i was trying to find the cause, but definitely not efficient as you do. 
otherwise i am not able to run the temply command locally, to validate the fix before creating the PR. 

`python temply/temply.py --keep-template -o log4j2-spring.xml log4j2-spring.xml.tpl
Traceback (most recent call last):
  File "temply/temply.py", line 4, in <module>
    import jinja2
  File "/usr/local/lib/python3.8/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/usr/local/lib/python3.8/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/usr/local/lib/python3.8/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.8/site-packages/markupsafe/__init__.py)`

**Comment by amannocci** [comment]
You need to install dependencies in your python environment. You can run ´pip3 install -r requirement.txt'.

**Comment by yinan-symphony** [comment]
👍   thx @amannocci
